# Generated by Django 3.2.8 on 2021-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_miduser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True),
        ),
    ]
