# Generated by Django 3.2.8 on 2021-11-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
