# Generated by Django 3.2.8 on 2021-11-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_projectfile_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('Cm', 'Cm'), ('C#', 'C#'), ('C#m', 'C#m'), ('D', 'D'), ('Dm', 'Dm'), ('D#', 'D#'), ('D#m', 'D#m'), ('E', 'E'), ('Em', 'Em'), ('F', 'F'), ('Fm', 'Fm'), ('F#', 'F#'), ('F#m', 'F#m'), ('G', 'G'), ('Gm', 'Gm'), ('G#', 'G#'), ('G#m', 'G#m'), ('A', 'A'), ('Am', 'Am'), ('A#', 'A#'), ('A#m', 'A#m'), ('B', 'B'), ('Bm', 'Bm')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tempo',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
