# Generated by Django 3.2.8 on 2021-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211115_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='miduser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
