import random

ADJECTIVES = [
    "adorable", "adventurous", "aggressive", "agreeable", "alert", "alive",
    "amused", "angry", "annoyed", "annoying", "anxious", "arrogant", "ashamed",
    "attractive", "average", "awful", "bad", "beautiful", "better",
    "bewildered", "black", "bloody", "blue", "blue eyed", "blushing",
    "bored", "brainy", "brave", "breakable", "bright", "busy", "calm",
    "careful", "cautious", "charming", "cheerful", "clean", "clear", "clever",
    "cloudy", "clumsy", "colorful", "combative", "comfortable", "concerned",
    "condemned", "confused", "cooperative", "courageous", "crazy", "creepy",
    "crowded", "cruel", "curious", "cute", "dangerous", "dark", "dead",
    "defeated", "defiant", "delightful", "depressed", "determined",
    "different", "difficult", "disgusted", "distinct", "disturbed", "dizzy",
    "doubtful", "drab", "dull", "eager", "easy", "elated", "elegant",
    "embarrassed", "enchanting", "encouraging", "energetic", "enthusiastic",
    "envious", "evil", "excited", "expensive", "exuberant", "fair", "faithful",
    "famous", "fancy", "fantastic", "fierce", "filthy", "fine", "foolish",
    "fragile", "frail", "frantic", "friendly", "frightened", "funny", "gentle",
    "gifted", "glamorous", "gleaming", "glorious", "good", "gorgeous",
    "graceful", "grieving", "grotesque", "grumpy", "handsome", "happy",
    "healthy", "helpful", "helpless", "hilarious", "homeless", "homely",
    "horrible", "hungry", "hurt", "ill", "important", "impossible",
    "inexpensive", "innocent", "inquisitive", "itchy", "jealous", "jittery",
    "jolly", "joyous", "kind", "lazy", "light", "lively", "lonely", "long",
    "lovely", "lucky", "magnificent", "misty", "modern", "motionless", "muddy",
    "mushy", "mysterious", "nasty", "naughty", "nervous", "nice", "nutty",
    "obedient", "obnoxious", "odd", "old-fashioned", "open", "outrageous",
    "outstanding", "panicky", "perfect", "plain", "pleasant", "poised", "poor",
    "powerful", "precious", "prickly", "proud", "putrid", "puzzled", "quaint",
    "real", "relieved", "repulsive", "rich", "scary", "selfish", "shiny",
    "shy", "silly", "sleepy", "smiling", "smoggy", "sore", "sparkling",
    "splendid", "spotless", "stormy", "strange", "stupid", "successful",
    "super", "talented", "tame", "tasty", "tender", "tense", "terrible",
    "thankful", "thoughtful", "thoughtless", "tired", "tough", "troubled",
    "ugliest", "ugly", "uninterested", "unsightly", "unusual", "upset",
    "uptight", "vast", "victorious", "vivacious", "wandering", "weary",
    "wicked", "wide-eyed", "wild", "witty", "worried", "worrisome", "wrong",
    "zany", "zealous"
]

NOUNS = ["account", "act", "adjustment", "advertisement", "agreement", "air",
         "amount", "amusement", "animal", "answer", "apparatus", "approval",
         "argument", "art", "attack", "attempt", "attention", "attraction",
         "authority", "back", "balance", "base", "behavior", "belief", "birth",
         "bit", "bite", "blood", "blow", "body", "brass", "bread", "breath",
         "brother", "building", "burn", "burst", "business", "butter",
         "canvas", "care", "cause", "chalk", "chance", "change", "cloth",
         "coal", "color", "comfort", "committee", "company", "comparison",
         "competition", "condition", "connection", "control", "cook", "copper",
         "copy", "cork", "copy", "cough", "country", "cover", "crack",
         "credit", "crime", "crush", "cry", "current", "curve", "damage",
         "danger", "daughter", "day", "death", "debt", "decision", "degree",
         "design", "desire", "destruction", "detail", "development",
         "digestion", "direction", "discovery", "discussion", "disease",
         "disgust", "distance", "distribution", "division", "doubt", "drink",
         "driving", "earth", "edge", "education", "effect", "end", "error",
         "event", "example", "exchange", "existence", "expansion",
         "experience", "expert", "fact", "fall", "family", "father", "fear",
         "feeling", "fiction", "field", "fight", "fire", "flame", "flight",
         "flower", "fold", "food", "force", "form", "friend", "front", "fruit",
         "glass", "gold", "government", "grain", "grass", "grip", "group",
         "growth", "guide", "harbor", "harmony", "hate", "hearing", "heat",
         "help", "history", "hole", "hope", "hour", "humor", "ice", "idea",
         "impulse", "increase", "industry", "ink", "insect", "instrument",
         "insurance", "interest", "invention", "iron", "jelly", "join",
         "journey", "judge", "jump", "kick", "kiss", "knowledge", "land",
         "language", "laugh", "low", "lead", "learning", "leather", "letter",
         "level", "lift", "light", "limit", "linen", "liquid", "list", "look",
         "loss", "love", "machine", "man", "manager", "mark", "market", "mass",
         "meal", "measure", "meat", "meeting", "memory", "metal", "middle",
         "milk", "mind", "mine", "minute", "mist", "money", "month", "morning",
         "mother", "motion", "mountain", "move", "music", "name", "nation",
         "need", "news", "night", "noise", "note", "number", "observation",
         "offer", "oil", "operation", "opinion", "order", "organization",
         "ornament", "owner", "page", "pain", "paint", "paper", "part",
         "paste", "payment", "peace", "person", "place", "plant", "play",
         "pleasure", "point", "poison", "polish", "porter", "position",
         "powder", "power", "price", "print", "process", "produce", "profit",
         "property", "prose", "protest", "pull", "punishment", "purpose",
         "push", "quality", "question", "rain", "range", "rate", "ray",
         "reaction", "reading", "reason", "record", "regret", "relation",
         "religion", "representative", "request", "respect", "rest", "reward",
         "rhythm", "rice", "river", "road", "roll", "room", "rub", "rule",
         "run", "salt", "sand", "scale", "science", "sea", "seat", "secretary",
         "selection", "self", "sense", "servant", "sex", "shade", "shake",
         "shame", "shock", "side", "sign", "silk", "silver", "sister", "size",
         "sky", "sleep", "slip", "slope", "smash", "smell", "smile", "smoke",
         "sneeze", "snow", "soap", "society", "son", "song", "sort", "sound",
         "soup", "space", "stage", "start", "statement", "steam", "steel",
         "step", "stitch", "stone", "stop", "story", "stretch", "structure",
         "substance", "sugar", "suggestion", "summer", "support", "surprise",
         "swim", "system", "talk", "taste", "tax", "teaching", "tendency",
         "test", "theory", "thing", "thought", "thunder", "time", "tin", "top",
         "touch", "trade", "transport", "trick", "trouble", "turn", "twist",
         "unit", "use", "value", "verse", "vessel", "view", "voice", "walk",
         "war", "wash", "waste", "water", "wave", "wax", "way", "weather",
         "week", "weight", "wind", "wine", "winter", "woman", "wood", "wool",
         "word", "work", "wound", "writing", "year"
         ]


def generate_random_project_name():
    return "{} {}".format(random.choice(ADJECTIVES),
                          random.choice(NOUNS)).capitalize()
